spring:
    datasource:
        url: jdbc:mysql://localhost:3306/qlsv
        username: root
        password: 123456
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        open-in-view: true
server:
    port: 8080
logging:
    level:
        root: DEBUG
        org.springframework: DEBUG
        org.hibernate: DEBUG
        com.example.qlsv_oop_group3: DEBUG{


