
# Đã chuyển cấu hình datasource sang application.properties, nên comment hoặc xóa phần dưới để tránh xung đột.
# spring:
#     datasource:
#         url: jdbc:mysql://localhost:3306/qlsv
#         username: root
#         password: 123456
#     jpa:
#         hibernate:
#           ddl-auto: update
#         show-sql: true
#         properties:
#             hibernate:
#                 dialect: org.hibernate.dialect.MySQLDialect
#         open-in-view: true
#     jackson:


 #spring:
  #   datasource:
   #      url: jdbc:mysql://localhost:3306/qlsv
    #     username: root
     #    password: 123456
     #jpa:
      #   hibernate:
       #    ddl-auto: update
        # show-sql: true
         #properties:
          #   hibernate:
           #      dialect: org.hibernate.dialect.MySQLDialect
         #open-in-view: true
     #jackson:


