spring:
    datasource:
        url: jdbc:mysql://localhost:3306/QLSV
        username: root
        password: 123456
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: true


